### ISSUE TITLE
Umbrella does not build

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-umbrella#104]
http://services.typefox.io/open-source/jenkins/job/xtext-umbrella/job/master/
https://ci.eclipse.org/xtext/job/xtext-umbrella/job/master/

**Comment by cdietrich** [comment]
(already broke last night, versions for jupiter/junit.platform and opentestj have changed)

**Comment by kthoms** [comment]
Removed version qualifiers for JUnit libraries, as we do in the SDK target definitions also.
