### ISSUE TITLE
Trigger sign-and-deploy job on successful build on JIRO

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-umbrella#106]
The job for xtext-umbrella should automatically trigger the [`sign-and-deploy`](https://ci.eclipse.org/xtext/job/releng/job/sign-and-deploy/) job with the required parameters under these conditions:
- the build was successful
- the build was on a release branch
  - branch name starts with `release_`
  - branch name matches `milestone_\d+\.\d+\.\d+\.(?:RC|M)\d+`
     (note that it is possible to have a Beta milestone which should not trigger a release, e.g. `milestone_2.17.0.Beta`
- the build runs on JIRO (JENKINS_URL contains `ci.eclipse.org/xtext`)

**Comment by cdietrich** [comment]
doesnt https://ci.eclipse.org/xtext/job/xtext-release/ have parameters?

**Comment by kthoms** [comment]
It has parameters, but they could be passed in.

**Comment by cdietrich** [comment]
@Hejado do i see it correct that this is obsolete now?

**Comment by Hejado** [comment]
Maybe not quite. It might be worth considering even on JIRO.

When umbrella-master finishes successfully on a releasing branch, sign-and-deploy could be triggered automatically.

**Comment by cdietrich** [comment]
@kthoms what do you think?

**Comment by kthoms** [comment]
This has been added for 2.20 with PR https://github.com/eclipse/xtext-umbrella/pull/181
