### ISSUE TITLE
Restructure Eclipse features

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-umbrella#12]
See the discussion on eclipse/xtext#1085. It would be good to move some of the Eclipse features to upstream repositories, e.g. org.eclipse.xtend.sdk.feature to xtext-xtend. This would require some restructuring, e.g. convert feature inclusion to feature dependency and break some features into smaller pieces.

**Comment by cdietrich** [comment]
i will close this as wontfix for now
