### ISSUE TITLE
Move Oomph setup from xtext-eclipse

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-umbrella#13]
The Oomph setup should be moved from [xtext-eclipse/releng/org.eclipse.xtext.contributor](https://github.com/eclipse/xtext-eclipse/blob/master/releng/org.eclipse.xtext.contributor/Xtext.setup) into this repository. It should be in the same folder as the [gradle-composite](https://github.com/eclipse/xtext-umbrella/tree/master/releng/gradle-composite). I propose to create a new folder `development` for these two.

**Comment by kthoms** [comment]
Before this the open PRs to the setup should be integrated:
https://github.com/eclipse/xtext-eclipse/pull/146
https://github.com/eclipse/xtext-eclipse/pull/142

After this, a first PR should copy the setup to the new location. Then we have to raise a bug for Oomph to use the new location. The old setup can only be removed after the setup's URL has changed in the Eclipse catalog.

**Comment by cdietrich** [comment]
this is obsolete with the monorepo
