### ISSUE TITLE
[simrel] Contribution for 2019-06

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-umbrella#132]
Is there a reason why  instead of release 2.18.0  an older milestone is contributed to the eclipse 2019-06? Or am I just missing something?  

See also https://www.eclipse.org/lists/xtext-dev/msg01317.html

**Comment by cdietrich** [comment]
the mailing list seems broken. never got that message

**Comment by cdietrich** [comment]
https://git.eclipse.org/r/#/c/143227/2/tmf-xtext.aggrcon never got merged.
and the mailing list is broken. did not get any of the two messages
created https://bugs.eclipse.org/bugs/show_bug.cgi?id=548387

**Comment by dhuebner** [comment]
I see..

**Comment by cdietrich** [comment]
@dhuebner  did you get any mail: on our side nobody got

**Comment by dhuebner** [comment]
@svenefftinge Shared the link with me. My last xtext-dev email is from 28.05

**Comment by cdietrich** [comment]
requested respin
https://www.eclipse.org/lists/cross-project-issues-dev/msg16759.html
but its likely too late

**Comment by cdietrich** [comment]
looks like gmail considered the mail or xtext-dev in general as spam => mails were in the spam folder in gmail

**Comment by cdietrich** [comment]
TODO what can we change in the release process to avoid such a mess in the future

**Comment by cdietrich** [comment]
respin was declined
