### ISSUE TITLE
Circular dependency when running composite build with Xtend compiler

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext-umbrella#14]
When I run the composite build including the Xtend compiler I get the following output:
```
[composite-build] Configuring build: /Users/spoenemann/github/xtext/xtext-core
[composite-build] Configuring build: /Users/spoenemann/github/xtext/xtext-extras
[composite-build] Configuring build: /Users/spoenemann/github/xtext/xtext-idea
[composite-build] Configuring build: /Users/spoenemann/github/xtext/xtext-lib
[composite-build] Configuring build: /Users/spoenemann/github/xtext/xtext-web

FAILURE: Build failed with an exception.

* What went wrong:
Failed to build artifacts for build 'xtext-lib'
> Circular dependency between the following tasks:
  :org.eclipse.xtend.lib:classes
  \--- :org.eclipse.xtend.lib:compileJava
       +--- :org.eclipse.xtend.lib:generateXtext
       |    +--- :org.eclipse.xtend.lib:jar
       |    |    \--- :org.eclipse.xtend.lib:classes (*)
       |    +--- :org.eclipse.xtend.lib.macro:jar
       |    |    \--- :org.eclipse.xtend.lib.macro:classes
       |    |         \--- :org.eclipse.xtend.lib.macro:compileJava
       |    |              +--- :org.eclipse.xtend.lib.macro:generateXtext
       |    |              |    +--- :org.eclipse.xtend.lib:jar (*)
       |    |              |    +--- :org.eclipse.xtend.lib.macro:jar (*)
       |    |              |    \--- :org.eclipse.xtext.xbase.lib:jar
       |    |              |         \--- :org.eclipse.xtext.xbase.lib:classes
       |    |              |              \--- :org.eclipse.xtext.xbase.lib:compileJava
       |    |              |                   \--- :org.eclipse.xtext.xbase.lib:generateXtext
       |    |              |                        +--- :org.eclipse.xtend.lib:jar (*)
       |    |              |                        +--- :org.eclipse.xtend.lib.macro:jar (*)
       |    |              |                        \--- :org.eclipse.xtext.xbase.lib:jar (*)
       |    |              \--- :org.eclipse.xtext.xbase.lib:jar (*)
       |    \--- :org.eclipse.xtext.xbase.lib:jar (*)
       +--- :org.eclipse.xtend.lib.macro:jar (*)
       \--- :org.eclipse.xtext.xbase.lib:jar (*)
  
  (*) - details omitted (listed previously)
```

It works when I add the flag `-PskipXtendCompiler=true` (see eclipse/xtext-extras#96).  Maybe we can configure the composite build to always activate that flag?

**Comment by kthoms** [comment]
Same issue when using "Refresh all Dependencies" in Buildship. I think it is mandatory then to have this option on by default.

**Comment by kthoms** [comment]
Fixed via ad270965671268c91e88474ca8487d4f5d6bd90e

**Comment by kthoms** [comment]
OK, then it is just a workaround. I could not find an appropriate place to fix it.
What about inverting the logic, i.e. include Xtend compile only if a property is set?

**Comment by kthoms** [comment]
I leave the solution up to you.

**Comment by spoenemann** [comment]
At the moment it is not possible to set a property in the composite build that is passed to included builds. I changed the default setting of the Xtend compiler to not be included, and it can be enabled with `-PcompileXtend=true` in each subproject, but the default is `false`. Me could consider changing the default back to `true` when a Gradle release is available that allows setting that property for the subprojects. An even better solution would be to change the dependency resolution in the composite build so the Xtend compiler classpath can be resolved properly without pointing to local projects (which leads to the cycle problem), but I doubt that will be possible.

**Comment by oehme** [comment]
> An even better solution would be to change the dependency resolution in the composite build so the Xtend compiler classpath can be resolved properly without pointing to local projects (which leads to the cycle problem), but I doubt that will be possible.

This bootstrapping use case is very common. We will definitely tackle that at some point.
