### ISSUE TITLE
Buildship fails to refresh gradle projects

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-umbrella#18]
**replace XTEXT_GRADLE_PROJECTS with a dynamically generated list since user can give project whatever name in oomph**

Run fresh Oomph setup with xtext umbrella and xtext eclipse models. Trying to refresh project configurations fails with:

```
FAILURE: Build failed with an exception.

* What went wrong:
Included build 'xtext-extras' is not unique in composite.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

CONFIGURE FAILED
```

```
Caused by: org.gradle.api.GradleException: Included build 'xtext-extras' is not unique in composite.
	at org.gradle.internal.composite.CompositeBuildSettingsLoader.validateBuildNames(CompositeBuildSettingsLoader.java:84)
	at org.gradle.internal.composite.CompositeBuildSettingsLoader.getIncludedBuilds(CompositeBuildSettingsLoader.java:76)
	at org.gradle.internal.composite.CompositeBuildSettingsLoader.findAndLoadSettings(CompositeBuildSettingsLoader.java:50)
	at org.gradle.initialization.NotifyingSettingsLoader.findAndLoadSettings(NotifyingSettingsLoader.java:33)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:148)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:36)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:118)
	... 42 more
```

**Comment by cdietrich** [comment]
Can you dump how your file system structure looks like

**Comment by dhuebner** [comment]
@cdietrich Which folder? root?

**Comment by cdietrich** [comment]
no i mean inside git.

you can enhance the settings.gradle in releng/gradle-composite and add a println like

```
if (!hasProperty('generatePrefs')) {
	(files { file('../../../').listFiles() })
.filter { 
    File it ->
    it.isDirectory() && XTEXT_GRADLE_PROJECTS.split(',').any{p->it.name.contains(p)} && new File(it, "settings.gradle").exists()
}.each {
    File it ->
    println(it)
    includeBuild it
}
}
```

thus you can see what the composite tries to include

**Comment by cdietrich** [comment]
well it looks like the following bites us:

```
XTEXT_GRADLE_PROJECTS=xtext-lib,xtext-core,xtext-extras,xtext-idea,xtext-web,xtext-xtend
```

(introduced on your request)

**Comment by cdietrich** [comment]
i assume if you can name the project `princess` or `hugo` we would even need some better guessing as before. @oehme do you have an idea?

**Comment by cdietrich** [comment]
since i have no idea i cannot fix this

**Comment by kthoms** [comment]
This multi-repo build has to have some assumptions on the project structure. Shouldn't this just be documented in contrib guide?
I am concerned that we do more and more magic to satisfy the gradle tooling.

**Comment by oehme** [comment]
I don't get what the problem is so I can't help you here. Doesn't look related to checkout structure since you are explicitly listing the directories to include.

**Comment by dhuebner** [comment]
@cdietrich in my ~/git/ folder I have 
```
xtext-extras
xtext-extras-master
```

maybe this cause the issue.

For the xtext repo I have also repo per branch folders :
```
xtext-maintenance
xtext-master
xtext-restructuring
```

**Comment by cdietrich** [comment]
Yes but I have no clue how you get that nor how to solve that

**Comment by dhuebner** [comment]
@cdietrich  You can imagine that one could have more than one xtext-extras repository (or what ever xtext repository) cloned into the ~/git directory, right?  In this situation the umbrella script won't work. Even if you say take only the first match, you will end up in an undefined workspace state where e.g. repositories from maintenance and master streams are mixed.

As you do not have a solution for that, give me a possibility to disable this "feature"

**Comment by cdietrich** [comment]
Yes but then you should not use oomph and buildship

**Comment by cdietrich** [comment]
So what about you giving @oehme hints on how to reproduce so that he can help us fix the gradle files

**Comment by dhuebner** [comment]
I can use Oomph and buildship if I remove the settings.gradle script

**Comment by cdietrich** [comment]
Yes and no you want have a composite build then

**Comment by cdietrich** [comment]
Won't

**Comment by cdietrich** [comment]
And having the composite build is the only reason we are doing this at all

**Comment by dhuebner** [comment]
@cdietrich I don't care about a composite build. I need a compile-error free workspace with /xtext-umbrella/pom.xml in it.

**Comment by cdietrich** [comment]
So you will do the server roundtrip all the time?

**Comment by dhuebner** [comment]
No

**Comment by cdietrich** [comment]
But this won't work. This is what we are discussing with miro and Stefan for 4month plus. Changes in core will not be used in extras web etc this way

**Comment by dhuebner** [comment]
So your solution for this issue is: "Don't import the xtext-umbrella project into eclipse workspace if you have buildship installed", right?

**Comment by cdietrich** [comment]
No the solution is to fix the settings and build gradle with some magic that matches umrella repo name to other repos names. But I have no clue how to do that if you can name xtext-core foo and xtext-extras bar

**Comment by cdietrich** [comment]
In git you have x umbrella projects and y others and you have to match them . If you have an algorithm for that we have won

**Comment by dhuebner** [comment]
@cdietrich Once again, can we have some kind of "try catch" or "disable" flag for that?

**Comment by cdietrich** [comment]
Not if you want to use composite builds and above you said yes I want to use composite builds

**Comment by dhuebner** [comment]
I want disable the code in settings.gradle or make it "not harm buildship" 
How can I do it without making changes in the repository files and the in the script itself?
I'm okay with extra oomph settings or setting properties in eclipse or even ENV variables

**Comment by cdietrich** [comment]
No you can't
If you disable settings you want have a composite build. You said you want a composite build @kthoms is it possible to dump a file with all repos in oomph

**Comment by cdietrich** [comment]
=> composite build needs

(1) build.gradle to connect components to composite
(2) settings.fradle to connect composite to its components

**Comment by oehme** [comment]
Okay I think I understand the problem now, you basically don't know the checkout structure at all. In that case you'll need to pass the list of project directories from Oomph to Gradle. No idea if Oomph offers that as a property or something.

**Comment by cdietrich** [comment]
yes i dont know neither. this is why i prefer to have separate dir foreach oomph setup

**Comment by cdietrich** [comment]
i am currently experimenting with generating a properties file from oomph.
looks promising
