### ISSUE TITLE
Investigate why build fails with 0.0.0 as junit version in target

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-umbrella#196]

**Comment by cdietrich** [comment]
will go with the workaround of explicit version in target for now

**Comment by cdietrich** [comment]
@miklossy did you find out anything?

**Comment by miklossy** [comment]
I did not investigate.

**Comment by cdietrich** [comment]
seems to be a tycho bug. with 2.3 its working.

**Comment by cdietrich** [comment]
can be done now
