### ISSUE TITLE
Feature org.eclipse.xtext.runtime (2.10) requires org.eclipse.xpand

### ISSUE THREAD

**Issue by gevegab** [eclipse/xtext-umbrella#20]
While trying to build (using tycho) a self contained update site of my project that contains the minimal xtext runtime dependencies, I created a target platform referencing http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.10.0 and including only the feature org.eclipse.xtext.runtime

I had some problems with missing requirements, see https://www.eclipse.org/forums/index.php/m/1752634/#msg_1752634 but I finally  got it working.

However, I noticed that there is a hard requirement of the feature on org.eclipse.xpand which seemed weird to me, as I thought Xpand has been replaced by Xtend2

Is this normal? do I need some transitive dependencies from xpand at runtime?

**Comment by spoenemann** [comment]
Xpand is required by `org.eclipse.xtext.generator`, which is deprecated but still used by those who haven't migrated to `org.eclipse.xtext.xtext.generator` yet. We can't remove that dependency without breaking a lot of users. That might be something for Xtext 3.0.0.

**Comment by cdietrich** [comment]
Couldn't we offer a second runtime feature?

**Comment by kthoms** [comment]
I don't think that it is user friendly to have a mess of features.
Could another option be to make the dependency optional, although effectively isn't for users of `org.eclipse.xtext.generator`?

**Comment by spoenemann** [comment]
> Could another option be to make the dependency optional

Even then Tycho will fetch Xpand because `org.eclipse.xtext.generator` has a dependency on it. The dependency on the feature doesn't make any difference AFAIK.

**Comment by kthoms** [comment]
The removal of the old generator is a clear task for a potential Xtext 3.0.0 (no, it is not planned yet). Can we close the question for now?

**Comment by gevegab** [comment]
I opened this question by recommendation of cdietrich on the forum to investigate the reasons of the dependency.

If you all agree that this can be postponed until the old generator can be removed, I can close the question at your will
