### ISSUE TITLE
new branches dont build

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-umbrella#223]
new branches dont build
https://ci.eclipse.org/xtext/job/xtext-umbrella/job/cd_xxxxneuneuneu/1/console
https://ci.eclipse.org/xtext/job/xtext-umbrella/job/cd_fixOrbitUpdate/1/

**Comment by cdietrich** [comment]
am not sure if other branches have same problem

**Comment by Hejado** [comment]
> groovy.lang.MissingPropertyException: No such property: JDK_VERSION for class: groovy.lang.Binding

Hang on

**Comment by cdietrich** [comment]
do we need defaults for choices? why is it working on others then?

**Comment by Hejado** [comment]
Fixed it: https://ci.eclipse.org/xtext/job/xtext-umbrella/job/cd_xxxxneuneuneu/2/console

**Comment by cdietrich** [comment]
yes restarting fixes it. but it is bad to run everthing twice

**Comment by Hejado** [comment]
I will use your Branch for the PR.

> why is it working on others then?

Maybe I missed the error in this PR, I'm not sure.

**Comment by Hejado** [comment]
> yes restarting fixes it. but it is bad to run everthing twice

I didn't just restart; i made a change. I will test my change with a new branch before creating the PR

**Comment by cdietrich** [comment]
ok

**Comment by Hejado** [comment]
https://ci.eclipse.org/xtext/job/xtext-umbrella/job/npr_test/1/console

okay, my bad. i misinterpreted the error.

**Comment by Hejado** [comment]
https://ci.eclipse.org/xtext/job/xtext-lib/job/npr_test1/1/console

The main difference seems to be that xtext-lib does not try to read JDK_VERSION for the javaVersion() function. 

> do we need defaults for choices? 

You can't set a default for choices. Well, you can (and we do), but it's just the first value of the array.

**Comment by Hejado** [comment]
https://ci.eclipse.org/xtext/job/xtext-umbrella/job/npr_test2/1/console

okay, that did it; PR coming now

**Comment by kthoms** [comment]
Thanks Nico!
