### ISSUE TITLE
Make Sign&Deploy more safe

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-umbrella#237]
understand how nexus splits up stuff to one or multiple repo.
make sure we can restart nexus deployment for releases aka dont delete branches immediately

**Comment by NicoPrediger** [comment]
I do not want to go back to manually deleting branches. I'd suggest to use the `input` step for deleting branches. This will "pause" the pipeline for a while. We can then check if Nexus accepts our release and decide to either continue or abort the pipeline.

I have no idea why nexus sometimes splits our staging repos, though. It mostly does not happen, and even when it does, it mostly works.

**Comment by NicoPrediger** [comment]
As this is happening again for the release, we've gained some new info and filed this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=569288

**Comment by cdietrich** [comment]
the eclipse team does say we have only one ip.
maybe we can enable debug logging in gradle
to see more information what is going wrong when we need retries.
maybe we also can open and sonatype issue.
therefore it would be helpful to reproduce this without the pressure of an actual milestone and release..
maybe we can start building fake milestones/releases and never publish them (e.g. remove the eclipse part of the proces)

@NicoPrediger @kthoms what do you think?

**Comment by NicoPrediger** [comment]
Agreed. We could create a debug-branch with a shortened Jenkinsfile for sign-and-deploy and enabled debug logging.

Would do that before opening an issue with sonatype, too.

**Comment by cdietrich** [comment]
https://issues.sonatype.org/browse/OSSRH-63268

**Comment by cdietrich** [comment]
the s01.oss instance  is currently not working

- use normal oss for snapshots
- for staging
  - i assume we need new server and auth entries in settings/security.xml (needs to be done by foundation staff)
- as we use normal oss for inter build deps and in the wizard, domainmodel, mydsl .... i propose that we keep this at normal oss @kthoms @szarnekow what do you think

**Comment by cdietrich** [comment]
ok we got s01.oss running for now.
looks promising 
lets observe with m3 and release

**Comment by cdietrich** [comment]
of course it let maven central explode
https://www.eclipse.org/forums/index.php/t/1106853/
commented on the jira

**Comment by cdietrich** [comment]
maven central works again: TBD: observe with M3 and R

**Comment by NicoPrediger** [comment]
M3 worked fine; I think we should close this issue as it seems to be fixed.
