### ISSUE TITLE
SimRel Tests: Get rid off Buckminster

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-umbrella#58]
The [simrel-tests job](https://ci.eclipse.org/xtext/job/simrel-tests) uses still Buckminster and a non-master branch from the cbi-analyzer repository.

Xtext should use tycho-surefire to produce test results.

![screenshot 11](https://user-images.githubusercontent.com/265597/38678805-64b76c10-3e62-11e8-8714-81fa7aebc477.png)
![screenshot 12](https://user-images.githubusercontent.com/265597/38678806-64f1d666-3e62-11e8-9e76-8563b35e4e07.png)

**Comment by cdietrich** [comment]
@kthoms what is the state of this issue?

**Comment by kthoms** [comment]
That was done. We don't use Buckminster there anymore.

The simrel tests are implemented in xtext-umbrella/releng/org.eclipse.xtext.releng.simrel.tests
