### ISSUE TITLE
Adjust Scripts miss releng/pom stuff in gradle projects

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-umbrella#65]

**Comment by cdietrich** [comment]
might affect https://github.com/TypeFox/gradle-plugins/

**Comment by szarnekow** [comment]
This will become obsolete with the changes by @kthoms I guess. Otherwise, please reopen.

**Comment by kthoms** [comment]
Not yet, pom's are not touched. Eventually it should become obsolete, but this is another step likewise the target definitions.

**Comment by kthoms** [comment]
Fixed in 2.16
